# Generated by Django 6.1 on 2026-08-12 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("reorder_level", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="inventory.category",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "name"),
                        name="unique_item_name_per_category",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gte", 0)),
                        name="item_quantity_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reorder_level__gte", 0)),
                        name="item_reorder_level_gte_0",
                    ),
                ],
            },
        ),
    ]
