# Generated by Django 6.1 on 2026-08-12 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("IN", "Stock in"), ("OUT", "Stock out")], max_length=3
                    ),
                ),
                ("quantity_moved", models.PositiveIntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="inventory.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "transaction history",
                "ordering": ["-timestamp", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity_moved__gt", 0)),
                        name="transaction_quantity_moved_gt_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("transaction_type__in", ["IN", "OUT"])),
                        name="transaction_type_valid",
                    ),
                ],
            },
        ),
    ]
