# Generated by Django 6.1 on 2026-08-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_transactionhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="quantity",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
