# Generated by Django 6.1 on 2026-08-15 15:22

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def normalize_existing_catalog_names(apps, schema_editor):
    Category = apps.get_model("inventory", "Category")
    Item = apps.get_model("inventory", "Item")

    category_updates = []
    category_names = {}
    for category in Category.objects.all().only("id", "name"):
        normalized_name = " ".join((category.name or "").split())
        if not normalized_name:
            raise RuntimeError(
                f"Category {category.pk} has a blank name."
            )

        comparison_key = normalized_name.casefold()
        conflicting_id = category_names.get(comparison_key)
        if conflicting_id is not None:
            raise RuntimeError(
                "Categories "
                f"{conflicting_id} and {category.pk} have conflicting "
                f"names after normalization: {normalized_name!r}."
            )

        category_names[comparison_key] = category.pk
        category_updates.append((category.pk, normalized_name))

    item_updates = []
    item_names = {}
    for item in Item.objects.all().only("id", "category_id", "name"):
        normalized_name = " ".join((item.name or "").split())
        if not normalized_name:
            raise RuntimeError(f"Item {item.pk} has a blank name.")

        comparison_key = (item.category_id, normalized_name.casefold())
        conflicting_id = item_names.get(comparison_key)
        if conflicting_id is not None:
            raise RuntimeError(
                "Items "
                f"{conflicting_id} and {item.pk} have conflicting names "
                "in the same category after normalization: "
                f"{normalized_name!r}."
            )

        item_names[comparison_key] = item.pk
        item_updates.append((item.pk, normalized_name))

    for category_id, normalized_name in category_updates:
        Category.objects.filter(pk=category_id).update(
            name=normalized_name
        )

    for item_id, normalized_name in item_updates:
        Item.objects.filter(pk=item_id).update(name=normalized_name)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_item_quantity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="item",
            name="unique_item_name_per_category",
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.RunPython(
            normalize_existing_catalog_names,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name="transactionhistory",
            index=models.Index(
                fields=["item", "-timestamp"], name="txn_item_timestamp_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="category_name_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                models.F("category"),
                django.db.models.functions.text.Lower("name"),
                name="item_category_name_ci_unique",
            ),
        ),
    ]
