# Generated by Django 6.1 on 2026-08-18 11:54

from django.db import migrations


PERMISSIONS = {
    ("category", "add_category"): "Can add category",
    ("category", "change_category"): "Can change category",
    ("category", "delete_category"): "Can delete category",
    ("category", "view_category"): "Can view category",
    ("item", "add_item"): "Can add item",
    ("item", "change_item"): "Can change item",
    ("item", "view_item"): "Can view item",
    (
        "item",
        "record_inventory_movement",
    ): "Can record inventory movement",
    ("item", "archive_item"): "Can archive item",
    ("item", "reactivate_item"): "Can reactivate item",
    (
        "transactionhistory",
        "view_transactionhistory",
    ): "Can view transaction history",
}

MANAGER_PERMISSIONS = tuple(PERMISSIONS)
STAFF_PERMISSIONS = (
    ("category", "view_category"),
    ("item", "view_item"),
    ("item", "record_inventory_movement"),
    ("transactionhistory", "view_transactionhistory"),
)
CUSTOM_PERMISSION_CODENAMES = (
    "record_inventory_movement",
    "archive_item",
    "reactivate_item",
)


def provision_inventory_groups(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    db_alias = schema_editor.connection.alias
    permissions = {}

    for (model, codename), name in PERMISSIONS.items():
        content_type, _ = ContentType.objects.using(db_alias).get_or_create(
            app_label="inventory",
            model=model,
        )
        permission, _ = Permission.objects.using(db_alias).get_or_create(
            content_type=content_type,
            codename=codename,
            defaults={"name": name},
        )
        permissions[(model, codename)] = permission

    manager, _ = Group.objects.using(db_alias).get_or_create(name="Manager")
    manager.permissions.set(
        [permissions[key] for key in MANAGER_PERMISSIONS]
    )

    staff, _ = Group.objects.using(db_alias).get_or_create(name="Staff")
    staff.permissions.set(
        [permissions[key] for key in STAFF_PERMISSIONS]
    )


def remove_inventory_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    db_alias = schema_editor.connection.alias

    Group.objects.using(db_alias).filter(
        name__in=("Manager", "Staff")
    ).delete()
    Permission.objects.using(db_alias).filter(
        content_type__app_label="inventory",
        content_type__model="item",
        codename__in=CUSTOM_PERMISSION_CODENAMES,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("inventory", "0005_remove_item_unique_item_name_per_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("record_inventory_movement", "Can record inventory movement"),
                    ("archive_item", "Can archive item"),
                    ("reactivate_item", "Can reactivate item"),
                ],
            },
        ),
        migrations.RunPython(
            provision_inventory_groups,
            remove_inventory_groups,
        ),
    ]
